name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Deploy code to server
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@143.198.87.246 "
          cd /Friday-Act-Backend &&
          git pull origin main &&
          npm install &&
          pm2 restart all  # or the command you use to restart your service
        "
