name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Deploy code via SSH
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 143.198.87.246  # Your server IP
        username: root         # Logging in as root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /path/to/your/project &&
          git pull origin main &&
          npm install &&
          pm2 restart all
